### ISSUE TITLE
OpenLogin + NLogin Converter

### ISSUE THREAD

**Issue by sprytex** [HaHaWTH/AuthMeReReloaded#240]
### What feature do you want to see added?

.

### Are there any alternatives?

LimboAuth

### Anything else?

.

**Comment by uSlashVlad** [comment]
You could migrate it manually in MySQL/MariaDB like this:

```sql
INSERT
	INTO
	minecraft.authme
SELECT
	ai as id,
	LOWER(last_name) as username,
	last_name as realname,
	password as password,
	last_ip as ip,
	UNIX_TIMESTAMP(last_seen) * 1000 as lastlogin,
        -- No player location info in nLogin plugin
	0 as x,
	0 as y,
	0 as z,
	'world' as world,
	UNIX_TIMESTAMP(creation_date) * 1000 as regdate,
	last_ip as regip, -- nLogin also doesn't store regip, last_ip placed here
	0 as yaw,
	0 as pitch,
	email as email,
	0 as isLogged,
	0 as hasSession,
	NULL as totp
FROM
	minecraft.nlogin n;
```

nLogin settings before migration (defaults):

```yaml
# Defaults:
database:
  table:
    account:
      table-name: "nlogin"
      columns:
        ai: "ai"
        last-name: "last_name"
        unique-id: "unique_id"
        mojang-id: "mojang_id"
        bedrock-id: "bedrock_id"
        password: "password"
        premium: "premium"
        last-ip: "last_ip"
        last-seen: "last_seen"
        creation-date: "creation_date"
        email: "email"
        discord: "discord"
        settings: "settings"
    data:
      table-name: "nlogin_data"
      columns:
        id: "id"
        key: "key"
        value: "value"

passwords:
  small: 5
  large: 32
  hashing:
    algorithm: "BCRYPT2A"
    bcrypt:
      rounds: 10
```

And AuthMe settings after migration (mostly defaults):

```yaml
DataSource:
    # Defaults here
    mySQLTablename: authme
    mySQLColumnId: id
    mySQLColumnName: username
    mySQLRealName: realname
    mySQLColumnPassword: password
    mySQLColumnSalt: ''
    mySQLColumnEmail: email
    mySQLColumnLogged: isLogged
    mySQLColumnHasSession: hasSession
    mySQLtotpKey: totp
    mySQLColumnIp: ip
    mySQLColumnLastLogin: lastlogin
    mySQLColumnRegisterDate: regdate
    mySQLColumnRegisterIp: regip
    mySQLlastlocX: x
    mySQLlastlocY: y
    mySQLlastlocZ: z
    mySQLlastlocWorld: world
    mySQLlastlocYaw: yaw
    mySQLlastlocPitch: pitch
    mySQLPlayerUUID: ''


ExternalBoardOptions:
    # This needs to be equal to passwords.hashing.bcrypt.rounds
    # Default in AuthMe is 12, default in nLogin is 10
    bCryptLog2Round: 10

settings:
    security:
        # This parameters needs to be equal to alternatives from nLogin
        minPasswordLength: 5  # passwords.small
        passwordMaxLength: 32 # passwords.large
        passwordHash: BCRYPT  # passwords.hashing.algorithm (BCRYPT = BCRYPT2A)
```

Everything works nice, passwords are validated correctly. Password hash doesn't equal, but it is normal for bcrypt since every hash is unique

---

Also tried to migrate as much data as possible with x, y, z fields from CoreProtect sessions logging: https://gist.github.com/uSlashVlad/3f467dd5d7c3a23aba2e415a1deec2b2
